chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'messages'
urlpatterns = [
    path("", InboxView.as_view()),
  
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from users.views import userlist

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('', TemplateView.as_view(template_name="home.html")),
    path('messages/', include('chat.urls')),
    path('userlist/', userlist, name='userlist')
]

pages/urls.py
from django.urls import path

from .views import HomePageView, userlist

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('userlist/', userlist.as_view(), name="userlist"),
]

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    username = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.email

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage
from users.models import *

class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

  


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView
from users.models import *

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

    


class userlist(TemplateView):
    template_name = 'pages/userlist.html'

    def get_context_data(self,**kwargs):
        context = super(userlist,self).get_context_data(**kwargs)
        context['object_list'] = CustomUser.objects.all()
        return context

users/views.py
from django.shortcuts import render
from .models import *
# Create your views here.



def userlist(request):
    userlist = CustomUser.objects.all()
  
    # userlist = 'ss'
    return render(request, 'user_list.html' , {'userlist': userlist})

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


<a  style="color: black;" href="/"> Back to chat  </a>

{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3 style="color: blue;" >{% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

    <li><span><span class="badge badge-pill badge-primary ">{{ chat.user.username }}</span> <span class="" style="font-size: 18px;">{{ chat.message }}</span></span></li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
    <input type="hidden" name="" id="myUsername" value="{{ user.username }} ">
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>

<script>
// websocket scripts
//console.log(window.location)
var fromData = $("#form")
var msgInput = $("id_message")

var chatHolder = $('chat-items')
var me = $('#myUsername').val()


var loc = window.location
var wsStart = 'ws://'
if (loc.protocol == 'http:'){
    wsStart = 'wss://'
}

// if (loc.protocol == 'https:'){
//     wsStart = 'wss://'
// }

var endpoint = wsStart + loc.host + loc.pathname
var socket = new ReconnectingWebSocket(endpoint)
// var socket = new webSocket(endpoint)
 

socket.onmessage = function(e){
    // console.log("message", e)
    var chatdataMsg = JSON.parse(e.data)
    

    chatHolder.append("<li>"+  msgText + "by-" + chatdataMsg.username + "</li>")
}




socket.onopen = function(e){ 
    console.log("open", e)
    fromData.submit(function(event){ 
        event.preventDefault()
        var msgText = msgInput.val()
        var finalData = {
            'message':msgText
        }
        socket.send(JSON.stringify(finalData))
        fromData[0].reset()
    })
}




 
socket.oneror = function(e){
    console.log("error", e)
}



socket.onclose = function(e){
    console.log("close", e)
}

 
socket.onmessage
socket.onopen
socket.onerror
socket.onclose

</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Welcome </title>
    {% include 'css.html' %}
</head>
<body>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>Welcome to chat server</h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

templates/base/header.html
{% load static %}
<nav>
    <ul>
    {% if user.is_authenticated %}
        <li style="float:right"><a class="active" href="{% url 'account_logout' %}">Log Out</a></li>
        <li style="float:left"><a class="" href="{% url 'home' %}"> Hi {{ user.username }}!</a></li>
    {% else %}
        <li style="float:left"><a class="" href="{% url 'home' %}"> Welcome</a></li>
        <li style="float:right"><a class="active" href="{% url 'account_login' %}">Log In</a></li>
    {% endif %}
    </ul>
</nav>

templates/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

<style>

body{
    background-color: black;
}


.container{
    background:
white;

padding-left: 25%;

padding-right: 10%;

margin: 5% 5%;

border: 1px solid blue;
}


</style>

templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% include 'base/header.html' %}
    {% block body %}
   
    {% if messages %}
    <div style="float:right;">
           <ul>
        {% for message in messages %}
        <li style="color: greenyellow;">{{message}}</li>
        
        {% endfor %}
      </ul>
    </div>
    {% endif %}




    {% block content %}
    {% endblock content %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}


    <!-- Optional JavaScript -->
  {% block javascript %}
  {% endblock javascript %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/js.html
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

templates/pages/home.html
{% extends 'index.html' %}
{% load static %}
{% block content%}
<br>
<center>
    <h1>Welcome !</h1>
    
    </center>

<br>

<div class="container">

<p>Click here for Chat </p>

<center>
    <a href="{% url 'userlist' %}"><button class="primaryAction button_black"  type="submit">Chat</button></a>
</center>  

</div>
{% endblock %}

templates/pages/userlist.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}

<div class="container">
    <center><h1>Users</h1></center>

<p style="color: white;">Chosse user to chat</p>
<ul>


    {% for user in object_list %}


   {% if user != request.user %}

   

   <li>  <a href="/messages/{{ user.username }}">{{ user.username }} </a> </li>
  
   <br>
   {% endif %}

    

    {% endfor %}


</ul>

</div>

{% endblock %}

templates/user_list.html
{% for i in userlist %}
{{ userlist.user }}

{% endfor %}